use_frameworks!

platform :ios, '9.0'

target 'TTCategories_Example' do
  pod 'TTCategories', :path => '../'

  target 'TTCategories_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
